### ISSUE TITLE
可以出一个详细使用教程吗？

### ISSUE THREAD

**Issue by Heporis** [nonPointer/ClashHelper#3]
包括GitHub action，推送到GitHub gist的流程。
在本地处理也报错，sites.yaml里的 group是指template.yaml里的proxy-groups？需要为每一个代理组写一段筛选参数？
![image](https://github.com/nonPointer/ClashHelper/assets/51895154/decd5a6c-5277-42a0-91cc-776d747e1d70)
还请出个详细教程，谢谢！

**Comment by nonPointer** [comment]
Github Action 配置如下

```yaml
name: Deploy to Gist

on:
  push:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: wget https://raw.githubusercontent.com/nonPointer/ClashHelper/master/helper.py -O helper.py 
      - run: python3 helper.py template.yaml Clash.yml | tee run.log
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: [gist id]
          file_path: [文件名]
          file_type: binary
```
创建一个自己账号下具有 Gist 读写权限的 API Token，设置到 repo 的 secrets 的 `TOKEN` 字段。

> sites.yaml 里的 group 是指 template.yaml 里的 proxy-groups

是的。你可以把多个来源的节点塞到同一个组里，也可以分为不同的组。配合分流规则，让流媒体走高质量（贵）的节点，上网走普通节点。

> 需要为每一个代理组写一段筛选参数

目前是的。你可以二次开发，根据需求进行修改。
